# template python-services cfg 
# copy this cfg to home dir ~/.python_auth_cfg.yml cfg
jenkins:
  admin_user      : ''
  admin_password  : ''
  jenkins_url     : 'https://examle.com'

selenoid_remote:
  username        : ''
  basic_url       : 'https://examle.com'
  password        : ''
